msg1: Hello World
msg2: From
msg3: Tyndorael

namespace: arknights

replicaCount: 1

image:
  repository: us.gcr.io/tynsoft/ark-operators
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  internalPort: 3000

imagePullSecrets: gcr-json-key

resources: {}