namespace: arknights

replicaCount: 1

image:
  repository: us.gcr.io/tynsoft/ark-operators
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  internalPort: 3000
  externalPort: 3000

imagePullSecrets: gcr-json-key

test: Hello

ingress:
  enabled: true
  annotations:     
    kubernetes.io/ingress.class: kong
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart.local
      paths:
        - path: /foo/.*
          backend:
            serviceName: test
            servicePort: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}