name: 'Deploy'
on:
  workflow_dispatch:  # manual trigger
  push:
    branches:
    - master

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v1'

    - name: 'Deploy'
      # Parameters are pulled directly from the GitHub deployment event so the
      # configuration for the job here is very minimal.
      uses: 'deliverybot/helm@master'
      with:
        version: '${{ github.sha }}'
        chart: 'chart'
        release: 'ark-operators-release'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'